title: "Stories by DeMers"  # Your website's title
description: "A personal website by B.A. DeMers"  # Short site description
url: "https://storiesbydemers.on-fleek.app" # During local development
baseurl: "" # Empty if not hosting in a subdirectory
author:
  name: "B.A. DeMers"  # Your name
lang: "en-US"
timezone: "America/Los_Angeles"

 # Full URL to your website
exclude: ["vendor/bundle/", "node_modules/", "tmp/", "log/", ".jekyll-cache", "Gemfile.lock", "Gemfile", "vendor/cache", "vendor/gems", "vendor/ruby"]
  
permalink: pretty  # URL structure (pretty or date)
navigation:  # Define your site's navigation menu
  - name: "Home"
    url: "/"  # Root path
  - name: "About"
    url: "/about/"  # About page path
  - name: "Blog"
    url: "/blog/"  # Blog page path
  - name: "Contact"
    url: "/contact/"  # Contact page path
  - name: "Stories"
    url: "/stories/"  # Stories page path

destination: dist  # Output directory

build:
  command: |
    gem install bundler:2.3.14
    bundle install
    bundle exec jekyll build